apiVersion: v1
kind: ImageStream
metadata:
  name: nextcloud-base
spec:
  imagePullPolicy: IfNotPresent
  tags:
  - annotations:
      openshift.io/display-name: nextcloud-base
      openshift.io/imported-from: docker.io/nextcloud:13.0.4-apache
    from:
      kind: DockerImage
      name: 'docker.io/nextcloud:13.0.4-apache'
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""

---
apiVersion: v1
kind: ImageStream
metadata:
  name: nextcloud
  name: nextcloud-build
spec:
  tags:
  - name: latest
---

apiVersion: v1
kind: BuildConfig
metadata:
  name: "nextcloud-build"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "nextcloud-build:latest"
  source:
    git:
      uri: http://github.com/project616/nextcloud-okd.git
      ref: "master"
    sourceSecret:
      name: "buildbot-auth"
      #contextDir: nextcloud
  images:
  - from:
      kind: "ImageStreamTag"
      name: "nextcloud-build:latest"
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: "ImageStreamTag"
        name: "nextcloud-base:latest"
  triggers:
    - type: "ImageChange"
    - type: "ConfigChange"

