apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
    variant: blue
  name: nextcloud
  namespace: nextcloud-standalone
spec:
  ports:
  - name: nextcloud-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: nextcloud-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: nextcloud
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
