apiVersion: v1
kind: Template
metadata:
  name: nextcloud
  annotations:
    description: "Nextcloud deployment"
    tags: "nextcloud"

parameters:

- name: NXCLOUD_DEV_NAMESPACE
  description: "NXCLOUD DEV NAMESPACE"
  required: true
  value: "nextcloud-staging"

- name: NXCLOUD_PORT
  description: "Port of the nextcloud service"
  required: true
  value: "8080"

- name: NXCLOUD_HTTPS_PORT
  description: "Port of the nextcloud service"
  required: true
  value: "8443"

- name: NXCLOUD_REPLICA_COUNT
  description: "Replica Count of the nextcloud service"
  required: true
  value: "1"

- name: NXCLOUD_SERVICE
  description: "Service name to be used to reach nextcloud service"
  required: true
  value: "nextcloud-prod"

- name: NXCLOUD_CONFIGMAP
  description: "Configmap containing nextcloud configuration"
  required: true
  value: nextcloud-config-prod

- name: HOSTNAME_SUFFIX
  description: "Suffix of the hostname used for routing traffic"
  required: true
  value: "<YOURDOMAIN>"

objects:

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nextcloud
      variant: prod
    name: nextcloud
  spec:
    host: nextcloud-prod${HOSTNAME_SUFFIX}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    wildcardPolicy: None
    to:
      kind: Service
      name: nextcloud-prod
      weight: "100"
    wildcardPolicy: None

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NXCLOUD_SERVICE}
      variant: blue
    name: ${NXCLOUD_SERVICE}
  spec:
    ports:
    - name: nextcloud-http
      port: "${{NXCLOUD_PORT}}"
      protocol: TCP
      targetPort: "${{NXCLOUD_PORT}}"
    - name: nextcloud-https
      port: "${{NXCLOUD_HTTPS_PORT}}"
      protocol: TCP
      targetPort: "${{NXCLOUD_HTTPS_PORT}}"
    selector:
      deploymentconfig: ${NXCLOUD_SERVICE}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NXCLOUD_SERVICE}
    labels:
      app: ${NXCLOUD_SERVICE}
      variant: blue
  spec:
    selector:
      deploymentconfig: ${NXCLOUD_SERVICE}
    replicas: ${NXCLOUD_REPLICA_COUNT}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${NXCLOUD_SERVICE}
          deploymentconfig: ${NXCLOUD_SERVICE}
        name: ${NXCLOUD_SERVICE}
      spec:
        containers:
        - env:
          - name: ETCD
            value: "http://<ETCD_ENDPOINT>"
          - name: TARGET_FILE
            value: "/var/www/html/config/config.php"
          - name: ROOT_NODE
            value: "nextcloud"
          - name: ENTRY
            value: "/entrypoint.sh"
          image: ' '
          imagePullPolicy: Always
          name: nextcloud
          ports:
          - containerPort: "${{NXCLOUD_PORT}}"
            protocol: TCP
          - containerPort: "${{NXCLOUD_HTTPS_PORT}}"
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: "${{NXCLOUD_PORT}}"
            timeoutSeconds: 20
          resources: {}
          volumeMounts:
            - name: nextcloud-locks
              mountPath: /var/lock
            - name: nextcloud-run
              mountPath: /var/run
            - name: ${NXCLOUD_CONFIGMAP}
              mountPath: /usr/share/mycloud-config
            - name: configdir
              mountPath: /var/www/html/config
            - name: swiftrc
              mountPath: /usr/share/swiftrc
              readonly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
        volumes:
        - name: nextcloud-locks
          emptyDir: {}
        - name: nextcloud-run
          emptyDir: {}
        - name: configdir
          emptyDir: {}
        - name: swiftrc
          secret:
            secretName: swift-secret-prod
        - name: ${NXCLOUD_CONFIGMAP}
          configMap:
            name: ${NXCLOUD_CONFIGMAP}
            defaultMode: 0644
            items:
              - key: "config.php"
                path: "config.php"
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - nextcloud
        from:
         kind: ImageStreamTag
         name: nextcloud-build:prod-ready
