apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf

data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;

    error_log  /var/log/nginx/error.log warn;

    events {
        worker_connections 2048;
        use epoll;
    }

    http {
        include /etc/nginx/conf/mime.types;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log combined;
        error_log /var/log/nginx/error.log crit;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        sendfile on;
        keepalive_timeout 85;

        #gzip on;

        include /etc/nginx/conf.d/*.conf;
    }
