apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
stringData:
  server.crt: |-
    -----BEGIN CERTIFICATE-----
    MIIGETCCBPmgAwIBAgISBOfFXejrPne3yTO1Ui6qO3enMA0GCSqGSIb3DQEBCwUA
    MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
    ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODA5MDUwODM4MDhaFw0x
    ODEyMDQwODM4MDhaMB4xHDAaBgNVBAMMEyouYXBwcy5mYXN0Y2xvdWQuaXQwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDpkfjxqXoRSt/jLjMimgrZs1ll
    zM/s9SJcMYLqIileV8aztGOjcFKardrUI09tiNl0igTC7VrpdwCUIST61vylxGKM
    4nqOUZIVs3+hQ3frnVeluFsrxYYwFaf3zc3LmjT3Yg4zmW8E1I6liFYC0jyzUXIl
    Zlzt5K4yq8BNTqccVBlKjK/u8pYvfdM8bhqE9J+geMnT7GJeCqiDLam03OPrbOWC
    eBMxTugqjtrPCzXX11uobb0D3Gey8t7i+EhmYYSVec+FbTNCxoObeVQA2zJ7W/u3
    16kZxU3Wn3vW9YruxgkY5kLhTu4oFLdkPPiF6T2uNApp+CzbOG1L4ukAkShJAgMB
    AAGjggMbMIIDFzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
    CCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFEVdJF+0BssY9P1KD05E
    uKK6AFz6MB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUF
    BwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNy
    eXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNy
    eXB0Lm9yZy8wHgYDVR0RBBcwFYITKi5hcHBzLmZhc3RjbG91ZC5pdDCB/gYDVR0g
    BIH2MIHzMAgGBmeBDAECATCB5gYLKwYBBAGC3xMBAQEwgdYwJgYIKwYBBQUHAgEW
    Gmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIGrBggrBgEFBQcCAjCBngyBm1Ro
    aXMgQ2VydGlmaWNhdGUgbWF5IG9ubHkgYmUgcmVsaWVkIHVwb24gYnkgUmVseWlu
    ZyBQYXJ0aWVzIGFuZCBvbmx5IGluIGFjY29yZGFuY2Ugd2l0aCB0aGUgQ2VydGlm
    aWNhdGUgUG9saWN5IGZvdW5kIGF0IGh0dHBzOi8vbGV0c2VuY3J5cHQub3JnL3Jl
    cG9zaXRvcnkvMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYA23Sv7ssp7LH+yj5x
    bSzluaq7NveEcYPHXZ1PN7Yfv2QAAAFlqRiiUgAABAMARzBFAiEAwWvOuf0jrJmD
    v+6KdtaIMGnzwHxtxu8RGB0yPlRcNXoCIGZezXunKtm/PqBLWHW1mULbzbLrAopq
    c50gXLy7Q37hAHYAKTxRllTIOWW6qlD8WAfUt2+/WHopctykwwz05UVH9HgAAAFl
    qRikSgAABAMARzBFAiEA7qFToy28cqkeeUiKPRpnMMHtR4dVl/+SkdIjrf3SyxIC
    IEpKVccIXrfDjDvhHzJYvP2lvYONP2aZfm6B/cO/U4y8MA0GCSqGSIb3DQEBCwUA
    A4IBAQBR8ktZ4Nwf134AqbbdzH8ob4n9OQiEMsBS3jKTMZ7hIDnokjDtxVPCn2Ll
    jyQmXEEBFnkTRkBaCCkmAZjURUVgcZpE39nD7dckr0Ay+cVGxCdgVi3wvNppku3/
    /0348lzaCcHzYli6EKZZB0vO8mc1m/0pcG62VuQV0i1PlmkHI0Q7ArpqWdZsR8oY
    r5HVKboAcK0Ybos5cZrVjbLBGXqVvRl46MK9dIH9zUusEnDDQTayMcYg5RAWbvm/
    LNvTqxBCeHEYO3eRlg552C5k2J9YzqwRHl1oRy8W1u1/Sv1RuSwn57CB7qGyBq/1
    c3l0H0zAeVbeCLKRezOjozCwfR3G
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGETCCBPmgAwIBAgISBOfFXejrPne3yTO1Ui6qO3enMA0GCSqGSIb3DQEBCwUA
    MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
    ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODA5MDUwODM4MDhaFw0x
    ODEyMDQwODM4MDhaMB4xHDAaBgNVBAMMEyouYXBwcy5mYXN0Y2xvdWQuaXQwggEi
    MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDpkfjxqXoRSt/jLjMimgrZs1ll
    zM/s9SJcMYLqIileV8aztGOjcFKardrUI09tiNl0igTC7VrpdwCUIST61vylxGKM
    4nqOUZIVs3+hQ3frnVeluFsrxYYwFaf3zc3LmjT3Yg4zmW8E1I6liFYC0jyzUXIl
    Zlzt5K4yq8BNTqccVBlKjK/u8pYvfdM8bhqE9J+geMnT7GJeCqiDLam03OPrbOWC
    eBMxTugqjtrPCzXX11uobb0D3Gey8t7i+EhmYYSVec+FbTNCxoObeVQA2zJ7W/u3
    16kZxU3Wn3vW9YruxgkY5kLhTu4oFLdkPPiF6T2uNApp+CzbOG1L4ukAkShJAgMB
    AAGjggMbMIIDFzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEG
    CCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFEVdJF+0BssY9P1KD05E
    uKK6AFz6MB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUF
    BwEBBGMwYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNy
    eXB0Lm9yZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNy
    eXB0Lm9yZy8wHgYDVR0RBBcwFYITKi5hcHBzLmZhc3RjbG91ZC5pdDCB/gYDVR0g
    BIH2MIHzMAgGBmeBDAECATCB5gYLKwYBBAGC3xMBAQEwgdYwJgYIKwYBBQUHAgEW
    Gmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIGrBggrBgEFBQcCAjCBngyBm1Ro
    aXMgQ2VydGlmaWNhdGUgbWF5IG9ubHkgYmUgcmVsaWVkIHVwb24gYnkgUmVseWlu
    ZyBQYXJ0aWVzIGFuZCBvbmx5IGluIGFjY29yZGFuY2Ugd2l0aCB0aGUgQ2VydGlm
    aWNhdGUgUG9saWN5IGZvdW5kIGF0IGh0dHBzOi8vbGV0c2VuY3J5cHQub3JnL3Jl
    cG9zaXRvcnkvMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYA23Sv7ssp7LH+yj5x
    bSzluaq7NveEcYPHXZ1PN7Yfv2QAAAFlqRiiUgAABAMARzBFAiEAwWvOuf0jrJmD
    v+6KdtaIMGnzwHxtxu8RGB0yPlRcNXoCIGZezXunKtm/PqBLWHW1mULbzbLrAopq
    c50gXLy7Q37hAHYAKTxRllTIOWW6qlD8WAfUt2+/WHopctykwwz05UVH9HgAAAFl
    qRikSgAABAMARzBFAiEA7qFToy28cqkeeUiKPRpnMMHtR4dVl/+SkdIjrf3SyxIC
    IEpKVccIXrfDjDvhHzJYvP2lvYONP2aZfm6B/cO/U4y8MA0GCSqGSIb3DQEBCwUA
    A4IBAQBR8ktZ4Nwf134AqbbdzH8ob4n9OQiEMsBS3jKTMZ7hIDnokjDtxVPCn2Ll
    jyQmXEEBFnkTRkBaCCkmAZjURUVgcZpE39nD7dckr0Ay+cVGxCdgVi3wvNppku3/
    /0348lzaCcHzYli6EKZZB0vO8mc1m/0pcG62VuQV0i1PlmkHI0Q7ArpqWdZsR8oY
    r5HVKboAcK0Ybos5cZrVjbLBGXqVvRl46MK9dIH9zUusEnDDQTayMcYg5RAWbvm/
    LNvTqxBCeHEYO3eRlg552C5k2J9YzqwRHl1oRy8W1u1/Sv1RuSwn57CB7qGyBq/1
    c3l0H0zAeVbeCLKRezOjozCwfR3G
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
    SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
    GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
    q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
    SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
    Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
    a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
    /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
    AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
    CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
    bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
    c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
    VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
    ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
    MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
    Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
    AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
    uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
    wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
    X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
    PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
    KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
    -----END CERTIFICATE-----
  server.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDpkfjxqXoRSt/j
    LjMimgrZs1llzM/s9SJcMYLqIileV8aztGOjcFKardrUI09tiNl0igTC7VrpdwCU
    IST61vylxGKM4nqOUZIVs3+hQ3frnVeluFsrxYYwFaf3zc3LmjT3Yg4zmW8E1I6l
    iFYC0jyzUXIlZlzt5K4yq8BNTqccVBlKjK/u8pYvfdM8bhqE9J+geMnT7GJeCqiD
    Lam03OPrbOWCeBMxTugqjtrPCzXX11uobb0D3Gey8t7i+EhmYYSVec+FbTNCxoOb
    eVQA2zJ7W/u316kZxU3Wn3vW9YruxgkY5kLhTu4oFLdkPPiF6T2uNApp+CzbOG1L
    4ukAkShJAgMBAAECggEAY8XKHJjzns1oI+hJSZ+ZwPL+3iCGNUdlfRJdRNyA5V8D
    byJAacGCV7aqQnIu7LBHi6OlcwrnCdGeuqgJ3ujVFY51No9MIN0xVPnPLDjg0hHt
    Lco5j9IZhxLJJG6SWUWvGHmXbW0+YkbWBFnfu+bIrSS+aMF4Mtq7msOJKrzNX6iw
    BubIrqA3BFNWDtVRpL7ailoObWAMiLP/htz90FwhI1vppPxSZwSf5GXTRWGGHYr/
    ueKC/bGrIKWLV1aPaoJTK0BfGh5VSLOkXMX6OOOk07UsxEPjl/Lvj1cp1rRE5/u2
    jakiFAkMW1k6IFVAfZDNM7gpd/n7N22NEDzqLSh8gQKBgQD6zjJEEDMcA3mjBOrs
    Q3aw3AQaJYC1KB1Jm/sc2XAHAcRe9dZkZ6RaLAzgjnBV6Y1cH5s4XZwJW0eL+VC+
    gx6uSrE/9H9gWtWsidCA53MWLWAxOVf7ibFeTX+Oqprt0kACfkqk+++6XMAs9q0o
    MWNDIm+o+mpQ4ud560eN6E6PUQKBgQDuaGR77ug/I6oJ2FLwa5IAkeGeEKonEDEz
    0x7ddmzEVkat9DF3mP++3LQAPXhlPROyG+/MydX0qnUR2conG7sNsX1KDevKQ5/G
    DBsMaLMkyZlIPsFySinVA5vJdMJQ2BScZXszsxEfghYwc0FdZQ3Nzm1XdTXg28mb
    lULTAXv7eQKBgQDstfvfHWL/h5Af+h43Sx0UozMD8m1djTTHKn6ApgADvPk3ntLw
    BJmruXOV5RnFHB8c2X/IXSFN+2a1h2Nby6kDWt+buwkVSeXtaEzvvIJ0ZfMpwjN1
    5mkO1hoT7pU27H8ZW1TcDiQeQjfmuBKJosNKs4+rbl01ZlKOUS9BkgXDYQKBgQCT
    SvfaAe6HI9eoIXiMhUk9BOQprg4R+FUNub/1/3aPjuY4DwiI5YQMPXsQMuoxUhzb
    C5uKIKEJek696pqUsvNMMH5BxHwLCOCrkUsczYrwjYUgN3V40Q0rSAF146cyH24M
    ej414MoRd2OSJ4MY2pg+sOyo/gd9lwzmDL+ucdpRsQKBgG5AZ09xZdQte8W4XGal
    Tk3n3GqmKOQssRmpgCS6f35j6bkaEWzzmhoVwN0xljFjI7uOfIa9v0rkLeSfIUn1
    Tl6Gft+NCrvm3lQOB3KXFb/OR+49+inNjJoEUzile4yyVrXlxySriCi4CbYJrlSB
    D5giDI37ZITjQ5Tnk+e6bv+H
    -----END PRIVATE KEY-----
